# 開発環境用のDocker Compose設定
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST=localhost:9099
      - NEXT_PUBLIC_FIRESTORE_EMULATOR_HOST=localhost:8081
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - FIREBASE_AUTH_EMULATOR_HOST=localhost:9099
      - FIRESTORE_EMULATOR_HOST=localhost:8081
    volumes:
      - ./backend:/app
    command: sh -c "pip install -r requirements.txt && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000" 