version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./backend/firebase-credentials.json:/app/firebase-credentials.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy

  # テスト用サービス
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: pytest -v --cov=app tests/
    volumes:
      - ./backend:/app
    environment:
      - TESTING=true

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm test
    volumes:
      - ./frontend:/app
    environment:
      - CI=true 